apiVersion: v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minha-api
  template:
    metadata:
      labels:
        app: minha-api
    spec:
      containers:
        - name: api
          image: minha-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
              name: api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type:
  selector:
    app: minha-api
  ports:
    - port: 80
      targetPort: 8080